const menuBtn=document.querySelector('.menu-btn');const navLinks=document.querySelector('.nav-links');menuBtn?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const finePointer=matchMedia('(pointer:fine)').matches;if(finePointer){document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${y*-7}deg) rotateY(${x*9}deg) translateY(-2px)`});card.addEventListener('mouseleave',()=>card.style.transform='')});document.querySelectorAll('.magnetic').forEach(btn=>{btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});btn.addEventListener('mouseleave',()=>btn.style.transform='')})}

const dateInput=document.querySelector('input[type="date"]');if(dateInput){const d=new Date();const yyyy=d.getFullYear();const mm=String(d.getMonth()+1).padStart(2,'0');const dd=String(d.getDate()).padStart(2,'0');dateInput.min=`${yyyy}-${mm}-${dd}`}
const form=document.getElementById('bookingForm');const status=document.getElementById('formStatus');form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);status.textContent=`✓ Thanks ${data.get('name')}! Your ${data.get('station')} request for ${data.get('date')} at ${data.get('time')} is ready for confirmation.`;form.reset()});
document.getElementById('year').textContent=new Date().getFullYear();

const canvas=document.getElementById('particles');const ctx=canvas.getContext('2d');let particles=[];const resize=()=>{canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const count=Math.min(70,Math.floor(innerWidth/22));particles=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.4+.35,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.15,a:Math.random()*.55+.15}))};resize();addEventListener('resize',resize);function animate(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(104,226,255,${p.a})`;ctx.fill()}requestAnimationFrame(animate)}if(!matchMedia('(prefers-reduced-motion: reduce)').matches)animate();

const soundBtn=document.getElementById('soundToggle');let audioCtx,soundOn=false;soundBtn?.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'♫':'♪';soundBtn.style.color=soundOn?'#b8ff5d':'#4defff';if(soundOn){audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator();const g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(440,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(660,audioCtx.currentTime+.09);g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.13);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.14)}});